### ISSUE TITLE
 Mismatch in the number of extracted patches compared to expected

### ISSUE THREAD

**Issue by Qing1Zhong** [clemsgrs/hs2p#13]
Hello @clemsgrs ,
I'm currently trying to replicate work done in Richard's [HIPT](https://github.com/mahmoodlab/HIPT) project. One critical step involves segmenting raw histopathological slides at 20x magnification into a series of regions with dimensions **[4096, 4096]**. I chose to use hs2p to accomplish this task.

**Steps to Reproduce:**
1. I downloaded a raw slide ([TCGA-2F-A9KO-01Z-00-DX1.195576CF-B739-4BD9-B15B-4A70AE287D3E.svs](https://portal.gdc.cancer.gov/files/30e4624b-6f48-429b-b1d9-6a6bc5c82c5e)) from the TCGA database. Slide details are:

> Magnification: 40
> Level dimensions: ((135168, 105472), (33792, 26368), (8448, 6592), (2112, 1648))
> Level downsamples: (1.0, 4.0, 16.0, 64.0)

2. Loaded a [.pt file ](https://github.com/mahmoodlab/HIPT/tree/master/3-Self-Supervised-Eval/embeddings_slide_lib/embeddings_slide_lib/vit256mean_tcga_slide_embeddings)containing segmentation details (obtained from **HIPT** repository):
```
import torch
wsi_path = 'TCGA-2F-A9KO-01Z-00-DX1.195576CF-B739-4BD9-B15B-4A70AE287D3E.pt'
wsi = torch.load(wsi_path)
print(wsi.shape)
```
Output: `torch.Size([30, 192])`
3. Ran patch_extraction.py from hs2p.

**Expected Result:**
I expected to get **30** patches of size [4096, 4096] based on the .pt file.
**Actual Result:**
The tiles.csv file generated has **398** coordinates, which is significantly different from what the .pt file from HIPT repository suggests.

**I wonder if there's something wrong with my parameter settings or if there's any other reason for this discrepancy. Any insights would be greatly appreciated. Thank you!**

**Parameters Used:**
```
slide_csv: '/home/xxx/CLAM/hs2p-master/slides.csv'
output_dir: 'output/debug' # folder where to save algorithm output
experiment_name: 'patch_extraction'
resume: False # whether or not to resume existing experiment

#backend: 'asap'
#backend: 'pyvips'
backend: 'openslide'

flags:
  patch: True # whether or not to extract patches from segmented tissue regions
  visu: True # whether or not to generate a .jpg image to visualize patching results
  verbose: False

seg_params:
  seg_level: -1 # downsample level on which to segment the WSI (-1 = uses the downsample level in the WSI closest to the following downsample parameter)
  downsample: 64 # if seg_level = -1, then uses this value to find the closest downsample level in the WSI for tissue segmentation computation
  sthresh: 8 # segmentation threshold (positive integer, using a higher threshold leads to less foreground and more background detection) (not used when use_otsu=True)
  mthresh: 7 # median filter size (positive, odd integer)
  close: 4 # additional morphological closing to apply following initial thresholding (positive integer)
  use_otsu: False # use otsu's method instead of simple binary thresholding
  save_mask: False # save tissue mask to disk as a .tif image
  visualize_mask: True # save a visualization of the tissue mask as a .jpg image
  tissue_pixel_value: 1 # value of tissue pixel in pre-computed segmentation masks

filter_params:
  ref_patch_size: 256 # reference patch size at spacing patch_params.spacing
  a_t: 100 # area filter threshold for tissue (positive integer, the minimum size of detected foreground contours to consider, relative to the reference patch size ref_patch_size, e.g. a value 10 means only detected foreground contours of size greater than 10 [ref_patch_size, ref_patch_size] sized patches at spacing patch_params.spacing will be processed)
  a_h: 16 # area filter threshold for holes (positive integer, the minimum size of detected holes/cavities in foreground contours to avoid, once again relative to the reference patch size ref_patch_size)
  max_n_holes: 10 # maximum of holes to consider per detected foreground contours (positive integer, higher values lead to more accurate patching but increase computational cost ; keeps the biggest holes)

vis_params:
  vis_level: -1 # downsample level to visualize the segmentation results (-1 = uses the downsample level in the WSI closest to the following downsample parameter)
  downsample: 64 # if vis_level = -1, then uses this value to find the closest downsample level in the WSI for tissue segmentation visualization
  downscale: 64 # downsample to visualize the result of patch extraction
  line_thickness: 200 # line thickness to draw the segmentation results (positive integer)

patch_params:
  spacing: 0.5 # pixel spacing (in micron/pixel) at which patches should be extracted (will find the level with spacing the closest to this value)
  patch_size: 4096 # patch size at previous pixel spacing
  overlap: 0.0 # percentage of overlap between two consecutive patches (float between 0 and 1)
  use_padding: True # whether to pad the border of the slide
  contour_fn: 'pct' # contour checking function to decide whether a patch should be considered foreground or background (choices between 'pct' - checks if the given patch has enough tissue using the following parameter as decision threshold, 'four_pt' - checks if all four points in a small grid around the center of the patch are inside the contour, 'center' - checks if the center of the patch is inside the contour, 'basic' - checks if the top-left corner of the patch is inside the contour)
  tissue_thresh: 0.1 # if contour_fn = 'pct', threshold used to filter out patches that have less tissue than this value (percentage)
  drop_holes: False # whether or not to drop patches whose center pixel falls withing an identified holes
  save_patches_to_disk: False # whether or not to save patches as images to disk
  format: 'jpg' # if save_patches_to_disk = True, then saves patches in this file format
  draw_grid: True # whether to draw the patch grid when visualizing patching results
  grid_thickness: 1 # sets the grid thickness ((in px) when visualizing patching results (256: 1, 4096: 2)
  bg_color: # which (r,g,b) values should be used to represent background when visualizing patching results
    - 214
    - 233
    - 238

speed:
  multiprocessing: True
  num_workers: 10 # number of process to start in parallel

wandb:
  enable: False
  project: 'hs2p'
  exp_name: '${experiment_name}'
  username: 'clemsg'
  dir: '/home/user'
  group:
  tags: []

# hydra
hydra:
  run:
    dir: /tmp/hydra_output

```
**Additional Question Regarding HIPT Replication:**
I noticed that you have successfully replicated the HIPT project. I have a question concerning the selection of histopathological slides for the self-supervised training in HIPT.

According to the paper, a total of 10,678 slides were used for training. It's clear that some slides from the TCGA database were discarded. Taking TCGA-BRCA as an example, the dataset has 1,133 slides, but I only found 1,038 .pt files for TCGA-BRCA in the HIPT repository. This indicates that close to 100 slides were not used.

Could you please shed some light on the criteria used for discarding certain slides? I'm curious to understand the rationale behind this selection process.

Thank you very much for your time and assistance.

**Willing to Discuss Further:**
I'm very interested in your work and would love to discuss it further. If you're open to it, could we perhaps continue this discussion via email? My email address is [1179152040@qq.com]. I look forward to potentially collaborating or at least learning more about your research and the hs2p project.

Thank you once again for your time and your contributions to the community.
